import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./Sidebar/Sidebar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${inter.variable} antialiased`}>
        <Sidebar />

        {/* কন্টেন্ট এরিয়া: ডেক্সটপে সাইডবারের সমান মার্জিন হবে (ml-[220px]) */}
        <main className="flex-1 lg:ml-55  lg:pt-0 min-h-screen">
          <div className="lg:pl-[36.5px]">{children}</div>
        </main>
      </body>
    </html>
  );
}
